""" added index to column item_id on table Item_History

Revision ID: 24091ad94d4c
Revises: 0cba80700d36
Create Date: 2025-09-25 15:07:19.348376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24091ad94d4c'
down_revision = '0cba80700d36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('Item_dealer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Dealer', ['dealer_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('Item_History', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Item_History_item_id'), ['item_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('Item_History_item_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'Item', ['item_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Item_History', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Item_History_item_id_fkey'), 'Item', ['item_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_Item_History_item_id'))

    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('Item_dealer_id_fkey'), 'Dealer', ['dealer_id'], ['id'])

    # ### end Alembic commands ###
